### ISSUE TITLE
Cours ISI3 

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp1-graph-piard-serrano#1]
Bonjour,

Le cours d'ISI3 est disponible à l'accueil de Polytech. Prenez en 30 (il faut en laisser 20 pour les alternants).

Je compte sur vous pour les faire circuler à toute la promotion. Et pour les avoir avec vous pendant les prochains TP.

**Comment by Slashgear** [comment]
c'est bon @clementserrano ?

**Comment by clementserrano** [comment]
oui c'est bon
