### ISSUE TITLE
Review code

### ISSUE THREAD

**Issue by clementserrano** [PolytechLyon/isi3-tp1-graph-piard-serrano#2]
Bonsoir M. Caron,

Que pensez-vous du code + rapport + organisation packages ?

Merci de votre retour.
Clément SERRANO.

**Comment by Slashgear** [comment]
- 👍 le rapport est bien complet

- [ ] C'est très bien l'algo DFS et BFS, mais sachez qu 'il existe déjà des types pour les queues et piles en java. Je ne vous oblige pas à le refaire mais donner moi un peu d'info sur ces types que vous semblez ignorer ?

- [ ] Ici le type pourrait être `IGraph`, pourquoi ? https://github.com/PolytechLyon/isi3-tp1-graph-piard-serrano/blob/d5a2e6e2d519b4ea2f9d7750d01c66e3d231908e/src/main/java/graph/UndirectedGraph.java#L10

- [ ] Node ne surcharge pas `hashcode`, quel est la conséquence ?

**Comment by Deyclan** [comment]
- Nous avons créé des objets Queue et Stack afin qu'ils implémentent notre interface QueueOrStack pour pouvoir factoriser le code contenu dans la classe GraphIterator. On y gère alors un objet QueueOrStack qui est initialisé en fonction du type de parcours que l'on appelle. 
Les types java que l'on "ignore" sont en réalité utilisés dans nos classes Queue et Stack. 

En java, l'objet Stack et l'interface Queue implémente/hérite de l'interface Collection. Cependant ils diffèrent dans leur comportement lors de l'ajout et la suppression d'objets : La stack ordonne suivant la méthode LIFO (Last-In-First-Out) tandis que dans la plus part des cas, la queue ordonne suivant la méthode FIFO (First-In-First-Out). 

- Si l'on change le type Graph en IGraph, les méthodes "addArc" et "hasArc" ne sont plus disponible dans l'objet graph... Par contre on peut changer le type Graph en IDirectedGraph, auquel cas il n'y a plus d'erreurs car l'intégralité des méthodes utilisées sont implémentées par les objets de type IUndirectedGraph 

- Node ne surchargeant pas la méthode hashcode, si on fait une deep copy d'un noeud, alors il n'aura pas le même hashcode que celui d'origine car il n'aura pas les mêmes cases mémoires d'allouées. Cela implique que dans notre GraphIterator, deux noeuds du graph pourraient éventuellement contenir les mêmes informations (label et id) sans pour autant être considérés comme étant identique. Et donc, visiter un des noeuds n'impliquerait pas que l'autre soit contenu dans la liste des noeuds visités 
[https://github.com/PolytechLyon/isi3-tp1-graph-piard-serrano/blob/d5a2e6e2d519b4ea2f9d7750d01c66e3d231908e/src/main/java/iterator/GraphIterator.java#L37](url)

**Comment by Slashgear** [comment]
très bien 😄
